SELECT * FROM PRODUTOS

--- CRIANDO A TABELA PARA O TESTE DE CHECK, QUE SERIA APENAS OS VALORES QUE PODEM COLOCAR NESTE EXEMPLO É AS UF
-- MG - SP - RJ ---

CREATE TABLE CIDADE (
    COD_CIDADE SMALLINT PRIMARY KEY,
    UF VARCHAR(2) NOT NULL CHECK (UF IN ('MG', 'SP', 'RJ'))
);

---- INSERINDO A UF QUE PODEM SER CADASTRADA ( MG, SP, RJ )
INSERT INTO CIDADE
(COD_CIDADE,UF)
VALUES
(20,'RJ');


----- CODIGO QUE NÃO INSERE DEVIDO A NÃO ESTA NA ISTA DAS QUE PODEM SER INSERIDA NESTE CASO USAMOS A UF 'RS'
INSERT INTO CIDADE
(COD_CIDADE,UF)
VALUES
(30,'RS');